# Basic Operations in Numpy

We can find the type of array, size of array, shape or array and dtype of elements 

Creating NumPy arrays and performing basic array operations

In [230]:
import numpy as np
arr=np.array([1,2,3,4,522,211,33,66,1,0],dtype='int32')

In [231]:
type(arr)

numpy.ndarray

In [232]:
arr.size

10

In [233]:
arr.astype('float')

array([  1.,   2.,   3.,   4., 522., 211.,  33.,  66.,   1.,   0.])

In [234]:
arr.astype('int8')

array([  1,   2,   3,   4,  10, -45,  33,  66,   1,   0], dtype=int8)

In [235]:
type(arr)

numpy.ndarray

We can create a python range into numpyy array

In [236]:
d1_array=np.arange(0,10,1)

In [237]:
d1_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [238]:
arra2=np.arange(10,0,-1)

In [239]:
arra2

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [240]:
d1_array.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [241]:
d1_array.shape

(10,)

In [242]:
d1_array.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [243]:
d1_array.shape

(10,)

In [244]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [245]:
np.full(10,6)

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [246]:
ones_array=np.ones((5,5))

In [247]:
zero_array=np.zeros_like(ones_array)

In [248]:
np.ones_like(zero_array)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [249]:
np.empty((10,2))

array([[ 1.        ,  1.47368421],
       [ 1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105],
       [ 3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474],
       [ 7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158],
       [ 9.52631579, 10.        ]])

In [250]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [251]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [252]:
as_array=[1,2,3,4,5,56,6]
np.asarray(as_array)

array([ 1,  2,  3,  4,  5, 56,  6])

In [253]:
float_array=np.linspace(1,9,15)

In [254]:
float_array

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        , 5.57142857, 6.14285714,
       6.71428571, 7.28571429, 7.85714286, 8.42857143, 9.        ])

In [255]:
float_array.astype('int32')

array([1, 1, 2, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 8, 9])

In [256]:
float_array.astype('int')

array([1, 1, 2, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 8, 9])

In [257]:
float_array*float_array

array([ 1.        ,  2.46938776,  4.59183673,  7.36734694, 10.79591837,
       14.87755102, 19.6122449 , 25.        , 31.04081633, 37.73469388,
       45.08163265, 53.08163265, 61.73469388, 71.04081633, 81.        ])

In [258]:
float_array.astype('int32')*2

array([ 2,  2,  4,  4,  6,  6,  8, 10, 10, 12, 12, 14, 14, 16, 18])

In [259]:
float_array

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        , 5.57142857, 6.14285714,
       6.71428571, 7.28571429, 7.85714286, 8.42857143, 9.        ])

In [260]:
float_array[3]

2.7142857142857144

In [261]:
int_arr=float_array.astype('int32')

In [262]:
int_arr+int_arr-1

array([ 1,  1,  3,  3,  5,  5,  7,  9,  9, 11, 11, 13, 13, 15, 17])

In [263]:
int_arr.size

15

In [264]:
d2_array=int_arr.reshape(3,5)

In [265]:
d2_array

array([[1, 1, 2, 2, 3],
       [3, 4, 5, 5, 6],
       [6, 7, 7, 8, 9]])

In [266]:
d2_array[1,3:]

array([5, 6])

In [267]:
d2_array[0:,3]

array([2, 5, 8])

In [268]:
int_arr

array([1, 1, 2, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 8, 9])

In [269]:
int_arr.size

15

In [270]:
d2_reshape=int_arr.reshape(5,3)

In [271]:
for i in range(0,5):
    d2_reshape[i]=i
    

In [272]:
d2_reshape

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [273]:
d2_reshape[3]

array([3, 3, 3])

In [274]:
d2_reshape.ravel()

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [275]:
d2_reshape[3]=99

In [276]:
d2_reshape

array([[ 0,  0,  0],
       [ 1,  1,  1],
       [ 2,  2,  2],
       [99, 99, 99],
       [ 4,  4,  4]])

In [277]:
d3_array=np.arange(1,21).reshape(2,10)

In [278]:
d3_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [279]:
d3_copy=d3_array.flatten()

In [280]:
d3_copy[6]=5

In [281]:
d3_array[0]=80

In [282]:
d3_array

array([[80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [283]:
resize_arra=np.arange(1,16).reshape(3,5)

In [284]:
resize_arra

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [285]:
new_arra=resize_arra.resize(1,15)

In [286]:
resize_arra

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [287]:
ar2d = np.arange(100)
ar2d.size

100

In [288]:
ar2d_copy=ar2d.reshape(10,10)

In [289]:
ar2d_copy

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

# Slicing

In [290]:
d3_array=np.arange(0,50).reshape(5,10)
d3_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [291]:
d3_array[2:,3:]

array([[23, 24, 25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49]])

# Indexing:
It is a process in which we target(access)indvidual or group of contagious values of ndarrays.

In [292]:
ar2d_copy[1,1]

11

In [293]:
ar2d_copy

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [294]:
ar2d_copy[4,-2:]

array([48, 49])

In [295]:
np.size(ar2d_copy,0)

10

# Fancy Indexing


In [303]:
# ar2d_copy[3:,[2,4,5]]
newarra2=ar2d_copy.reshape(25,2,2)
row=np.array([0,1])
col=np.array([1])
print(newarra2)
newarra2[1,row[:,np.newaxis],col]

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]

 [[24 25]
  [26 27]]

 [[28 29]
  [30 31]]

 [[32 33]
  [34 35]]

 [[36 37]
  [38 39]]

 [[40 41]
  [42 43]]

 [[44 45]
  [46 47]]

 [[48 49]
  [50 51]]

 [[52 53]
  [54 55]]

 [[56 57]
  [58 59]]

 [[60 61]
  [62 63]]

 [[64 65]
  [66 67]]

 [[68 69]
  [70 71]]

 [[72 73]
  [74 75]]

 [[76 77]
  [78 79]]

 [[80 81]
  [82 83]]

 [[84 85]
  [86 87]]

 [[88 89]
  [90 91]]

 [[92 93]
  [94 95]]

 [[96 97]
  [98 99]]]


array([[5],
       [7]])

In [ ]:
row=np.array([0,1,2])
col=np.array([1,0])
ar2d_copy[row[:,np.newaxis],col]

In [ ]:
X = np.arange(12).reshape((3, 4))
print(X)
mask=np.array([1,0,1,0],dtype='bool')
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row[:,np.newaxis],col ]


In [ ]:
X = np.arange(12).reshape((3, 4))
print(X)
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
print(X[row[:, np.newaxis], col])

# Stacks

In [ ]:
array1=np.arange(5,50).reshape(5,9)

In [ ]:
array1

In [ ]:
array2=np.arange(0,45).reshape(5,9)

In [ ]:
array2

In [ ]:
np.hstack((array1,array2))



In [ ]:
np.vstack((array2,array2))

In [ ]:
np.concatenate((array2,array1),axis=1)

In [ ]:
con=np.concatenate((array2,array1),0)
sp=con.reshape(9,10)
sp

# split 2d array


In [ ]:
print(sp)
ar=np.split(sp,[1,2],axis=1)
ar

# Statistical Functions


In [ ]:
statics = np.array([1,4,7,3,5,7,8,6,5,3,2,5,78], dtype=np.int64)
print(f'min value : {statics.min()}\nindex of min value : {statics.argmin()}\
\nmax value : {statics.max()}\nindex of max value : {statics.argmax()}')

In [ ]:
print(f'Mean is : {statics.mean()}\nStandard Daviation : {statics.std()}\nVariance is : {statics.var()}')

In [ ]:
x=np.arange(0,50,5)
y=np.arange(0,100,10)
x[1]=3
y[1]=1
print(x,y)
cov_matrix=np.stack((x,y),axis=0)

In [ ]:
# np.corrcoef(cov_matrix)
np.corrcoef(cov_matrix)

In [ ]:
print(np.corrcoef(cov_matrix))

# Logical operation

In [ ]:
(cov_matrix>1).all()

# Transposing


In [ ]:
cov_matrix.T

In [ ]:
in_array = [.5, 1.5, 2.5, 3.5, 4.5, 10.1] 
print ("Input array : \n", in_array) 
  
ceiloff_values = np.ceil(in_array) 
print ("\nRounded values : \n", ceiloff_values) 

In [ ]:
number = complex(3, 4) 
print(abs(number)) 

In [ ]:
matA=np.arange(2,20)

In [ ]:
matB=np.arange(2,20)

In [ ]:
np.dot(matA,matB)

In [ ]:
matA@matB

In [ ]:
matA-2